"""empty message

Revision ID: e241d6188db0
Revises: 
Create Date: 2020-11-21 18:21:39.971452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e241d6188db0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='equipmentstatus'), nullable=True),
    sa.Column('location', sa.Enum('BRAZIL', 'USA', 'JAPAN', name='equipmentlocation'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    op.drop_table('vessel')
    # ### end Alembic commands ###
